# Ghost Theme Development Configuration

[project]
name = "ghost-theme-development"
description = "Ghost theme customization for login system"

[commands]
# Git commands for file tracking
add = ["git", "add"]
status = ["git", "status"]
commit = ["git", "commit", "-m"]